### ISSUE TITLE
Психолого-медико-педагогическая комиссия (ПМПК)

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/soulalchemy#19]
http://ninjamock.com/Designer/Workplace/1681963/%D0%9F%D0%9C%D0%9F%D0%9A

График заседаний, Документы - в следующем таске.

**Comment by EijiMirai** [comment]
В каком следующем? Ссылку сразу скидывай, но в формате markdown

**Comment by iLucker93** [comment]
Документы  :    https://github.com/EijiMirai/soulalchemy/issues/20
