### ISSUE TITLE
График заседаний

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/soulalchemy#21]
http://ninjamock.com/Designer/Workplace/1681963/%D0%93%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B7%D0%B0%D1%81%D0%B5%D0%B4%D0%B0%D0%BD%D0%B8%D0%B9   

п.с  Заказчик хочет чтобы можно было пилить графики прямо из админ панели.

**Comment by EijiMirai** [comment]
Пошёл он нахер со своими графиками из панели)

За это пущай ещё столько же денег заплатит, если хочет подобный функционал.
Такое написать не хером махать.

**Comment by EijiMirai** [comment]
Пока что сделал тупо ссылкой, создание и вывод таблиц в формате таблиц, а не ссылки - будет оплачиваться отдельно. И дорого.
