### ISSUE TITLE
Руссифицировать левое меню в админке

### ISSUE THREAD

**Issue by EijiMirai** [EijiMirai/soulalchemy#6]
Я сам хз как это сделать.

**Comment by vk26** [comment]
я сделаю.

**Comment by EijiMirai** [comment]
Я уже начал, там даже примеры есть)

**Comment by vk26** [comment]
Я сделал через en.yml. Перевод activerecord
Assets\attachment не победил.

**Comment by EijiMirai** [comment]
Всё делается намного проще.
